import Head from "next/head";
import { Router } from "next/router";
import Banner from "../components/banner";
import Card from "../components/card";
import { fetchParishes } from "../lib/parishes";
// import Image from 'next/image'

// import parishesData from "../data/parishes.json";

import styles from "../styles/Home.module.css";

// export async function getStaticProps(context) {
//   return {
//     props: { parishes },
//   };
// }

export default function Home(props) {
  console.log(fetchParishes);

  const handleOnBannerBtnClick = () => {
    console.log("clicked");
    // TODO: fetch parishes
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Parochiæ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* <h1 className={styles.title}>Find Your Parish</h1> */}
        <Banner
          className="styles.buttonWrapper"
          handleOnClick={handleOnBannerBtnClick}
          buttonText="View parishes nearby"
        />
        {/* TODO: props.parishes.length from {fetchParishes}*/}
        {props.length > 0 && (
          <>
            <h2 className={styles.heading2}>Tokyo Parishes</h2>
            <div className={styles.cardLayout}>
              {props.parishes.map((parish) => (
                <Card
                  key={parish.fsq_id}
                  href={`/parish/${parish.fsq_id}`}
                  name={parish.name}
                  imgUrl={parish.imgUrl}
                  className={styles.card}
                />
              ))}
            </div>
          </>
        )}

        <div className={styles.grid}></div>
      </main>
    </div>
  );
}
