import Head from "next/head";
import Banner from "../components/banner";
import Card from "../components/card";
import styles from "../styles/Home.module.css";
import { fetchParishes } from "../lib/parishes";

export async function getStaticProps(context) {
  console.log("getStaticProps");

  const parishes = await fetchParishes();

  return {
    props: { parishes },
  };
}

export default function Home(props) {
  console.log("props", props);

  const handleOnBannerBtnClick = () => {
    console.log("clicked");
    // TODO: fetch parishes
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Parochiæ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* <h1 className={styles.title}>Find Your Parish</h1> */}
        <Banner
          className="styles.buttonWrapper"
          handleOnClick={handleOnBannerBtnClick}
          buttonText="View parishes nearby"
        />
        {props.parishes.length > 0 && (
          <>
            <h2 className={styles.heading2}>Tokyo Parishes</h2>
            <div className={styles.cardLayout}>
              {props.parishes.map((parish) => (
                <Card
                  key={parish.fsq_id}
                  href={`/parish/${parish.fsq_id}`}
                  name={parish.name}
                  imgUrl={parish.imgUrl}
                  className={styles.card}
                />
              ))}
            </div>
          </>
        )}

        <div className={styles.grid}></div>
      </main>
    </div>
  );
}
